version: "3.7"
services:
  backend:
    image: delivery_trans_api
    container_name: delivery_trans_api
    command: sh -c "yarn install && yarn run start:dev"
    restart: on-failure
    tty: true
    volumes:
      - ./backend:/app/backend/transactional_api
    depends_on:
      - db
    ports:
      - 8500:8500
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=delivery
      - HASH_SALTS=10
      - JWT_EXPIRATION_TIME=300
      - JWT_REFRESH_EXPIRATION_TIME=2592000
      - API_PORT=8500
  db:
    image: postgres:alpine3.18
    container_name: delivery_postgres
    restart: on-failure
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=delivery
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
networks:
  app-network:
    driver: bridge
